[[redirects]]
from = "/"
  to = "https://dallasisd.resourceexplorer.org"
  status = 301
  force=true
[[redirects]]
from = "/faq"
  to = "https://dallasisd.resourceexplorer.org/faq"
  status = 301
  force=true   
[[redirects]]
from = "/in-action/*"
  to = "https://dallasisd.resourceexplorer.org/in-action/:splat"
  status = 301
  force=true  
[[redirects]]  
from = "/about"
  to = "https://dallasisd.resourceexplorer.org/about"
  status = 301
  force=true  
[[redirects]]  
from = "/contact"
  to = "https://dallasisd.resourceexplorer.org/contact"
  status = 301
  force=true 
[[redirects]]  
from = "/explorer"
  to = "https://dallasisd.resourceexplorer.org/explorer"
  status = 301
  force=true  
[[redirects]]  
from = "/explorer"
  to = "https://dallasisd.resourceexplorer.org/get-the-data"
  status = 301
  force=true   
[[redirects]]  
from = "/schools/*"
  to = "https://dallasisd.resourceexplorer.org/schools/:splat"
  status = 301
  force=true    

  


