backend:
  name: git-gateway
  branch: staging
media_folder: "src/data/cms/img"
collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "./src/data/cms/yml/en_US/home.yml"
        fields: # update fields
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: markdown }
          - label: Team
            name: team
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Position, name: position, widget: string }
              - { label: Photo, name: photo, widget: image }
      - label: "Shared Strings"
        name: "shared"
        file: "./src/data/cms/yml/en_US/shared.yml"
        fields: # update fields
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: markdown }
          - label: Locations
            name: locations
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Address, name: address, widget: string }
  - label: "Posts"
    name: "posts"
    folder: "./src/data/cms/md/en_US/posts"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Intro, name: intro, widget: markdown } # update fields
